import turtle
screen=turtle.Screen()
width,height = screen.screensize()
screen.bgcolor('silver')
screen.title('거북이 프로그램')
turtle.setup (0.5,0.5)
print(screen.screensize())
#turtle.penup()
turtle.color('green')
turtle.forward(width-20)
turtle.goto(0,0)
turtle.backward(width-20)
turtle.goto(0,0)
turtle.left(90)
turtle.forward(height-90)
turtle.goto(0,0)
turtle.backward(height-90)
turtle.goto(0,0)
turtle.done()