import turtle
screen = turtle.Screen()
screen.title('거북이 프로그램')
print("윈도우 높이 : ", screen.window_height())
print("윈도우 너비 : ", screen.window_width())
# print(screen.screensize())
width,height = screen.screensize()
print("캔바스 높이 : ", height)
print("캔바스 너비 : ", width)
print("*" * 80)

screen.setup(650,650)
print("윈도우 높이 : ", screen.window_height())
print("윈도우 너비 : ", screen.window_width())

screen.screensize(600,600)
width,height = screen.screensize()
print("캔바스 높이 : ", height)
print("캔바스 너비 : ", width)
# print("캔바스 높이 : ", screen.canvheight)
# print("캔바스 너비 : ", screen.canvwidth)

turtle.penup()
turtle.goto(-300,300)
turtle.pendown()
turtle.forward(600)
turtle.right(90)
turtle.forward(600)
turtle.right(90)
turtle.forward(600)
turtle.right(90)
turtle.forward(600)
turtle.right(90)

turtle.penup()
turtle.home()
turtle.pendown()

turtle.exitonclick()